
package org.ykryukov.holidays.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HolidaysWebServiceImplService", targetNamespace = "http://ws.holidays.ykryukov.org/", wsdlLocation = "http://localhost:1986/wss/holidays?wsdl")
public class HolidaysWebServiceImplService
    extends Service
{

    private final static URL HOLIDAYSWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOLIDAYSWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HOLIDAYSWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.holidays.ykryukov.org/", "HolidaysWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/wss/holidays?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLIDAYSWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HOLIDAYSWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HolidaysWebServiceImplService() {
        super(__getWsdlLocation(), HOLIDAYSWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HolidaysWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLIDAYSWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HolidaysWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HOLIDAYSWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HolidaysWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLIDAYSWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HolidaysWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolidaysWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolidaysWebService
     */
    @WebEndpoint(name = "HolidaysWebServiceImplPort")
    public HolidaysWebService getHolidaysWebServiceImplPort() {
        return super.getPort(new QName("http://ws.holidays.ykryukov.org/", "HolidaysWebServiceImplPort"), HolidaysWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidaysWebService
     */
    @WebEndpoint(name = "HolidaysWebServiceImplPort")
    public HolidaysWebService getHolidaysWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.holidays.ykryukov.org/", "HolidaysWebServiceImplPort"), HolidaysWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLIDAYSWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HOLIDAYSWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HOLIDAYSWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
