
package org.ykryukov.holidays.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolidaysWebService", targetNamespace = "http://ws.holidays.ykryukov.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolidaysWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.holidays.ykryukov.org/HolidaysWebService/getHelloWorldRequest", output = "http://ws.holidays.ykryukov.org/HolidaysWebService/getHelloWorldResponse")
    public String getHelloWorld();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.holidays.ykryukov.org/HolidaysWebService/getHolidaysRequest", output = "http://ws.holidays.ykryukov.org/HolidaysWebService/getHolidaysResponse")
    public StringArray getHolidays();

}
